### ISSUE TITLE
adding animations in counts sections

### ISSUE THREAD

**Issue by trishit78** [Student-Chapter-CSE/SC-CSE_Official_website#24]
![img](https://github.com/Student-Chapter-CSE/SC-CSE_Official_website/assets/90523629/061d9f5b-7f39-4683-88be-7de9ec28851e)

adding animations in the number counts

**Comment by unixx0055** [comment]
Ok let me try

**Comment by trishit78** [comment]
assigned @unixx0055

**Comment by IndraniSom** [comment]
Great work @unixx0055
