### ISSUE TITLE
Make the Techquisitive page responsive

### ISSUE THREAD

**Issue by IndraniSom** [Student-Chapter-CSE/SC-CSE_Official_website#26]
Currently as you can see the techquisitive page is not responsive .So fix the mediaquery of this page.
![Screenshot from 2024-04-15 15-08-14](https://github.com/Student-Chapter-CSE/SC-CSE_Official_website/assets/121074944/c9e3355c-ae81-412d-9a51-89b3e8f5e2be)

**Comment by Rohan-450** [comment]
for the HTML component navigate to 
Client ->app->events->techquisitive->page.js

for the CSS component navigate to
client->style->events->techquisitive.module.css
(write the media query in this file probably 768px is the last limit for responsiveness)

**Comment by SouravKumbhakar** [comment]
Ok let me try👍

**Comment by IndraniSom** [comment]
your PR is merged successfully .great work
